apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: hello-world-tanzu
spec:
  build:
    buildpacks: {}
    path: ../..
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "21"
  ports:
  - name: main
    port: 8080
